### ISSUE TITLE
New repo for Spider gbXML Fixer 'Atrax' R2

### ISSUE THREAD

**Issue by theo-armour** [ladybug-tools/spider-gbxml-fixer#1]
@ladybug-tools/spiders 

# [Spider gbXML Fixer 'Atrax']( https://www.ladybug.tools/spider-gbxml-fixer/ )

![image](https://user-images.githubusercontent.com/547626/55768788-0f6acc00-5a33-11e9-953a-5311be0917b0.png)

_From the read me:_

[GbXML]( http://www.gbxml.org/About_GreenBuildingXML_gbXML ) data files follow an industry-standard format and used to the transfer 3D building project data between computer aided design (CAD) program and energy analysis programs. The good people who create CAD and energy analysis applications are primarily software programmers. They have infrequent access to large numbers of actual building test cases nor can they simulate large varieties of practice-specific energy simulation workflows. The current often-repeated outcome is that building engineering practices devote much time to dealing with issues in transferring data back and forth between CAD applications and energy analysis programs - and thus losing time for creating better simulations.

Many of the issues to be found in parsing gbXML files are clerical matters that may be identified using simple text search routines. Full 3D viewing of these types of errors is not needed and may actually slow things down.

The desired solution is a utility that enables seamless gbXML data transfer between applications without human intervention.

### Mission for Spider gbXML Fixer / currently

* Run basic text-based checks on gbXML files and uncover, identify, report and fix any errors or issues
* Help you access scripts that work well in your practice, your workflow and your skill set so that your projects are designed and built faster, cheaper and better

### Vision / future

* All errors are fixed and changes saved with the click of a single button or just running the script on a server

### Notes

* Not all issues in gbXML files are simple, text-based issues. Some issues will require full a 3D visualization in order to be discovered and fixed. An intention is to make the workflow between a text-based fixer and full 3D fixer as seamless as possible.
* If you identify a frequently occurring error in ggXML files and supply sample files that exhibit the error, the Spider team will be pleased to build a an open-source module that identifies and fixes your issues
* The script is still at an early stage. Many more checks may be added. The user interface needs streamlining. And so on.

**Comment by mostaphaRoudsari** [comment]
Congrats! This is very exciting! 🎉

**Comment by theo-armour** [comment]
@mdengusiak @EK-CEL @mechspec

Spider gbXML Fixer 'Atrax' 3.0.0 is up

Bookmark this link for always getting the latest version:
https://www.ladybug.tools/spider-gbxml-fixer/dev/

Bookmark this link for always getting the stable version:
https://www.ladybug.tools/spider-gbxml-fixer/

R3 begins to add nearly automatic fixers for these two fixers:

* Fix surfaces with invalid ExposedToSun values
* Fix surfaces with invalid surface type 

Both fixers are work-in-progress and still have issues, but you can begin to see where these modules are heading.

One obvious thing is that you want to see the errors fixed in 3D but Fixer won't do this. This is because the goal of Fixer is to fix errors with 100% accuracy with the push of a single button.

You will note that you can press a button for each issue found to see the attributes of the surface being edited. This is just to help you and me verify the fix during the early stages of development. In later versions, fingers crossed, this feedback won't be necessary.

![image](https://user-images.githubusercontent.com/547626/56011925-ebabbe00-5c9e-11e9-98cb-1d87cc402d9b.png)


***

This makes us ask: how will we verify the fixes in the future?  Easy. There will be a version of Maevia that allows you to open two models and view the differences all nicely highlighted.

***

I do understand that testing this module will end up being kind of boring, but having good feedback really speed up and tunes good development. Also it is a huge motivator for the developer. ;-)

**Comment by EvgenyK-SO** [comment]
@theo-armour 
The 'Save file' doesn't work for me: no dialog box, no file appearing on local drive.

**Comment by theo-armour** [comment]
@EK-CEL @mdengusiak 

Thanks Evgeny. Michal reported this earlier but I could not reproduce, but today I did reproduce.

Will fix ASAP

**Comment by theo-armour** [comment]
@EK-CEL 

Save file should be working now, but a lot of the fixers are having issues right now - so don't expect to be able to do much for the moment. ;-(
