### ISSUE TITLE
Spider gbXML Fixer R0.4.7: Fix surfaces with an extra adjacent space

### ISSUE THREAD

**Issue by mdengusiak** [ladybug-tools/spider-gbxml-fixer#5]
**Fix surfaces with an extra adjacent space**  - algorithm to be adjusted:

1. check adj space if two are different this take priority and adj space remain
2.  change surface type to InteriorType...
3. change CADObjectID to Spider default types:
there are types we will replace to..
`Basic Wall: SIM_INT_SLD SpiderFix [as in original element]`
`Basic Wall: SIM_INT_GLZ SpiderFix [as in original element]`
`Floor: SIM_INT_SLD_FLR SpiderFix [as in original element]`

4. for ElementID  [111111] in CADObectID we keep original
![image](https://user-images.githubusercontent.com/14005893/57567673-d9738b80-73d4-11e9-9a18-0eb09c1c19a3.png)

so in this example

we have: 
_surfaceType: ExteriorWall
exposedToSun: true
id: Panel-193
CADObjectId: Basic Wall : SIM_EXT_GLZ WA17 [1091386]_

we should fix to: 
_surfaceType: InteriorWall
exposedToSun: false
id: Panel-193
CADObjectId: Basic Wall : SIM_INT_GLZ SpiderFix [1091386]_

**Comment by theo-armour** [comment]
@mdengusiak 

Please try "Fix surfaces with two adjacent spaces & incorrect surface type" in R0.4.8

**Comment by mdengusiak** [comment]
@theo-armour 
I am testing now I think there is issue with path..in Maevia..
we have now:
`https://www.ladybug.tools/spider-gbxml-fixer/dev`

and  this works fine
`https://www.ladybug.tools/spider-gbxml-fixer`

**Comment by michaldengusiak** [comment]
I retested this and fine
