### ISSUE TITLE
Spider gbXML Fixer R0.4.7: Add Fix surfaces with incorrect CADObjectID

### ISSUE THREAD

**Issue by mdengusiak** [ladybug-tools/spider-gbxml-fixer#6]
**Fix surfaces with incorrect CADObjectID**  -  :
this is connected fix with _Get air surfaces with single adjacent space_

1. we have now: one adj space and ExeriorSurtfaceType
1. check if CADObjectID include "AIR" replace to SpiderDeafult for CADObjectID

`Basic Wall: SIM_EXT_SLD SpiderFix [as in original element]`
`Basic Roof: SIM_EXT_SLD SpiderFix  [as in original element]`
`Floor: SIM_EXT_SLD_FLR SpiderFix [as in original element]`

![image](https://user-images.githubusercontent.com/14005893/57567945-92879500-73d8-11e9-9883-9a2b2ab6e4cc.png)

so in our example
we have 
_surfaceType: Roof
exposedToSun: false
id: Panel-3051
CADObjectId: Floor: SIM_INT_AIR [1323050]
Name: Panel-3051
 AdjacentSpace
spaceIdRef: Space040_138VOID_ 

we should change to
_surfaceType: Roof
exposedToSun: false
id: Panel-3051
CADObjectId: Floor: Basic Roof: SIM_EXT_SLD SpiderFix [1323050]
Name: Panel-3051
 AdjacentSpace
spaceIdRef: Space040_138VOID_

**Comment by theo-armour** [comment]
@mdengusiak 

See:
## [ Spider gbXML Fixer 'Atrax' R0.4.12]( https://www.ladybug.tools/spider-gbxml-fixer/ )

Check out:

### Fix surfaces with two adjacent spaces & incorrect surface type

### Fix Surfaces with CAD object ID missing

Lookup table needs work:

https://github.com/ladybug-tools/spider-gbxml-fixer/blob/master/r0-4-0/gbx-gbxml-core.js#L103-L122

**Comment by michaldengusiak** [comment]
tested and approved
before
![image](https://user-images.githubusercontent.com/26113670/58153381-c7aca680-7c66-11e9-8509-f7de696fcae0.png)

after

![image](https://user-images.githubusercontent.com/26113670/58153428-e01cc100-7c66-11e9-9eb7-e74b579c3213.png)
