### ISSUE TITLE
Reducing information for look

### ISSUE THREAD

**Issue by EvgenyK-SO** [ladybug-tools/spider-gbxml-fixer#8]
After running all checks once of twice it is good to see the whole statistics for the file. But dealing with dozens of project it would be better to focus on problems. So it would be nice to:
1. Collapse all checks. The "Close all checks" button can be renamed to "Expand (or Unfold) all results".
2. Grey out the checks which have 0 problems.

**Comment by theo-armour** [comment]
@EK-CEL 

### [Spider gbXML Fixer 'Atrax' R0.4.13]( https://www.ladybug.tools/spider-gbxml-fixer/ )

![image](https://user-images.githubusercontent.com/547626/57965134-ab220e80-78f4-11e9-8ab2-fa8ee3bde448.png)

* 'Run all checks' button finishes with all checks closed
* 'Open all non zero' displays all checks where issues have been identified
* Numbers of issues found are highlighted

***

Thank you for having a look - and for making useful and actionable suggestions.

Have any of the checks actually found issues for you? And were the fixes useful.

**Comment by EvgenyK-SO** [comment]
Thank you for the update. The screen looks cleaner now. :) 
Sorry, is it possible not highlighting zeros? May be not showing them at all?

---

For our further calculations we have a software which is not sensible for most of the issues which the Spider identifies. We are interesting in fixing building envelope only. We understand that it is too minimalistic, but absolutely necessary. Please don't consider our approach as a typical workflow.

**Comment by theo-armour** [comment]
@EK-CEL 

## [Spider gbXML Fixer 'Atrax' R0.4.14]( https://www.ladybug.tools/spider-gbxml-fixer/ )

> not highlighting zeros?

Done

> We are interesting in fixing building envelope only.
> We understand that it is too minimalistic, but absolutely necessary. 
> Please don't consider our approach as a typical workflow.

I understand. A lot of the effort in Atrax is driven by @mdengusiak's needs (and hopefully the needs of others.)

Much of the initial effort on Fixer seems to be getting to be complete. This means that I can get back to Maevia where we can look at issues that need full 3D such as what is exterior or interior and the directions of normals and so on - which I hope will be of use to your office.
